### ISSUE TITLE
1px shift in status on Alacritty MacOS

### ISSUE THREAD

**Issue by baptisteArno** [catppuccin/tmux#254]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### Describe your problem.

There is a visual issue with the status modules.

### Paste your configuration.

.tmux.conf:

```sh
unbind r
bind r source-file ~/.config/tmux/tmux.conf

set -g prefix C-s 

set -g mouse on

set -sg escape-time 0

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tpm'

run '~/.tmux/plugins/tpm/tpm'
```

alacritty.yml:
```
env:
  TERM: xterm-256color

font:
  size: 16
  normal:
    family: "JetBrainsMono Nerd Font"
    style: Regular
  bold:
    style: Bold
  italic:
    style: Italic
  bold_italic:
    style: Bold Italic

window:
  dynamic_padding: false
  decorations: buttonless
  startup_mode: Maximized 

# Colors (Catpuccin Mocha: https://github.com/catppuccin/alacritty/blob/main/catppuccin-mocha.yml)
colors:
  primary:
    background: "#1E1E2E" # base
    foreground: "#CDD6F4" # text
    # Bright and dim foreground colors
    dim_foreground: "#CDD6F4" # text
    bright_foreground: "#CDD6F4" # text

  # Cursor colors
  cursor:
    text: "#1E1E2E" # base
    cursor: "#F5E0DC" # rosewater
  vi_mode_cursor:
    text: "#1E1E2E" # base
    cursor: "#B4BEFE" # lavender

  # Search colors
  search:
    matches:
      foreground: "#1E1E2E" # base
      background: "#A6ADC8" # subtext0
    focused_match:
      foreground: "#1E1E2E" # base
      background: "#A6E3A1" # green
    footer_bar:
      foreground: "#1E1E2E" # base
      background: "#A6ADC8" # subtext0

  # Keyboard regex hints
  hints:
    start:
      foreground: "#1E1E2E" # base
      background: "#F9E2AF" # yellow
    end:
      foreground: "#1E1E2E" # base
      background: "#A6ADC8" # subtext0

  # Selection colors
  selection:
    text: "#1E1E2E" # base
    background: "#F5E0DC" # rosewater

  # Normal colors
  normal:
    black: "#45475A" # surface1
    red: "#F38BA8" # red
    green: "#A6E3A1" # green
    yellow: "#F9E2AF" # yellow
    blue: "#89B4FA" # blue
    magenta: "#F5C2E7" # pink
    cyan: "#94E2D5" # teal
    white: "#BAC2DE" # subtext1

  # Bright colors
  bright:
    black: "#585B70" # surface2
    red: "#F38BA8" # red
    green: "#A6E3A1" # green
    yellow: "#F9E2AF" # yellow
    blue: "#89B4FA" # blue
    magenta: "#F5C2E7" # pink
    cyan: "#94E2D5" # teal
    white: "#A6ADC8" # subtext0

  # Dim colors
  dim:
    black: "#45475A" # surface1
    red: "#F38BA8" # red
    green: "#A6E3A1" # green
    yellow: "#F9E2AF" # yellow
    blue: "#89B4FA" # blue
    magenta: "#F5C2E7" # pink
    cyan: "#94E2D5" # teal
    white: "#BAC2DE" # subtext1

  indexed_colors:
    - { index: 16, color: "#FAB387" }
    - { index: 17, color: "#F5E0DC" }

key_bindings:
  - { key: Right, mods: Alt, chars: "\x1BF" }
  - { key: Left,  mods: Alt, chars: "\x1BB" }
```

### Attach screenshots.

![CleanShot 2024-07-18 at 11 56 40@2x](https://github.com/user-attachments/assets/d87e9e1a-9574-43a1-934d-efc14c6da5b9)

### What tmux version are you seeing the issue on?

tmux 3.4
