### ISSUE TITLE
Right side of status line looks jagged

### ISSUE THREAD

**Issue by AlphabetsAlphabets** [catppuccin/tmux#31]
Hello, I was wondering if I need to download any additional fonts as the status bat at the bottom looks a little weird, especially the right side.

![image](https://user-images.githubusercontent.com/44822875/212437786-8503150d-faf4-4648-9df7-e5dd58579fae.png)

**Comment by kolyamba2105** [comment]
Hey, @AlphabetsAlphabets 
May I ask you what font, terminal emulator and OS are you using?
I had a similar issue with these separators in `Alacritty` on `Mac OS` when I used `Iosevka Nerd Font`. I also tried other fonts, but the only font which doesn't have this issue is `JetBrains Mono Nerd Font`.

**Comment by AlphabetsAlphabets** [comment]
Hello @kolyamba2105 . My OS is Manjaro. Terminal emulator is alacritty. The font I'm using is JetBrainsMono.

**Comment by kolyamba2105** [comment]
> Hello @kolyamba2105 . My OS is Manjaro. Terminal emulator is alacritty. The font I'm using is JetBrainsMono.

Are you sure you're using the nerd font? You should have something like this in your `alacritty.yml`:

```yml
font:
  size: 14

  normal:
    style: Regular
    family: JetBrainsMono Nerd Font
```

It would be nice if you could share you alacritty config, however at this moment I don't really know what the problem might be. In my case it was invalid font rendering in alacritty on Mac OS, since you're not using Mac OS, then it's not the case for you.

**Comment by AlphabetsAlphabets** [comment]
```yml
font:
  normal:
    family: JetBrainsMono

  bold:
    family: JetBrainsMono
    style: Bold

  italics:
    family: JetBrainsMono
    style: Italic

  size: 9.0
```

This is my config for fonts @kolyamba2105

**Comment by AlphabetsAlphabets** [comment]
Adding `Nerd Font` to the end of each line managed to fix the issue. Thank you @kolyamba2105 

```yml
font:
  normal:
    family: JetBrainsMono Nerd Font

  bold:
    family: JetBrainsMono Nerd Font
    style: Bold

  italics:
    family: JetBrainsMono Nerd Font
    style: Italic

  size: 9.0
  ```
